version: '2'

services:
  db:
    image: postgres:14.6-alpine
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
